# Generated by Django 2.1 on 2018-11-04 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='articleContent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('article_content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='articleInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('aticle_name', models.CharField(max_length=32)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('modify_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='label',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label_name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='labelClassify',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='label',
            name='classify',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='repertory.labelClassify', to_field='name'),
        ),
        migrations.AddField(
            model_name='articleinfo',
            name='label',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='repertory.label', to_field='label_name'),
        ),
        migrations.AddField(
            model_name='articlecontent',
            name='article_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='repertory.articleInfo'),
        ),
    ]
