# Generated by Django 2.1 on 2018-11-05 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repertory', '0002_articleinfo_abstract'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articleinfo',
            old_name='aticle_name',
            new_name='article_name',
        ),
    ]
